const personawbr = [
  {"host": "flonkie.nekoweb.org", "username": "flonkie"},
  {"host": "layercake.moe", "username": "June"},
  {"host":"compendium.nekoweb.org","username":"Casio"},
  {"host":"dreamscape.place","username":"Xiaoshan"},
  {"host":"kellin09.nekoweb.org","username":"Mary Jane"},
  {"host":"nightcoreandcaffeine.neocities.org","username":"NightcoreAndCaffeine"},
  {"host":"cursedricardo.nekoweb.org","username":"CursedRicardo"},
  {"host":"angelroom.nekoweb.org","username":"angel"},
  {"host":"aliensriracha.neocities.org","username":"Aliensriracha"},
  {"host":"tuffgong.nekoweb.org","username":"Tuffground II"},
  {"host":"onlytrichromatic.neocities.org","username":"Kelly"},
  {"host":"kazeys.art","username":"kaz"},
  {"host":"fenris.nekoweb.org","username":"Fenris"},
  {"host":"26gk0.neocities.org","username":"26gk0"},
  {"host":"foxlore.neocities.org","username":"claudia"},
  {"host":"upsidedownhourglass.neocities.org","username":"lucas"},
  {"host":"divineintrusion.neocities.org","username":"Jace"},
  {"host":"necogutz.neocities.org","username":"necogutz"},
  {"host":"maralados.neocities.org","username":"marmar"},
  {"host":"mistakemp4.neocities.org","username":"Mistake"},
  {"host":"musubi.nekoweb.org","username":"Moriarty"},
  {"host":"hunipyon.neocities.org","username":"chara"},
  {"host":"albedo.nekoweb.org","username":"Sunny"},
  {"host":"scrapsite.nekoweb.org","username":"BigBanana"},
  {"host":"betapopsicle.neocities.org","username":"Betapop"},
   {"host":"yuriplanet.neocities.org","username":"anh"},
];

export default personawbr;